server:
  port: 8089

spring:
  application:
      name: source-gateway
  output:
    ansi:
      enabled: ALWAYS

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}-${eureka.instance.hostname}:${server.port}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/