server:
  port: 8761

spring:
  application:
    name: source-eureka
  output:
    ansi:
      enabled: ALWAYS

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
